coverage:
  range: 65...80
  notify:
    webhook:
      default:
        url: "https://codecov2discord.herokuapp.com/discord-webhook/331926555733524480/U6Lv0VVCHF0vsiwKZvGSaedAG7FBjMS6_HHAkPQb_gB6g25__NDgSx7v69IruQBYondg"

