language: android

jdk:

- oraclejdk8

install:

- echo yes | sdkmanager "tools"

- echo yes | sdkmanager "platform-tools"

- echo yes | sdkmanager "build-tools;27.0.3"

- echo yes | sdkmanager "platforms;android-27"

script:
- sudo apt install tree zip unzip -y

- ./gradlew tasks

- ./gradlew clean test build
- ls
- pwd
- cd app/build/reports/tests/testFullDebugUnitTest
- zip -r logs.zip *
- curl --upload-file ./logs.zip https://transfer.sh/logs.zip
- cd 
- cd app/build/
- ls
sudo: true

before_cache:

- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:

directories:

- $HOME/.gradle/caches/

- $HOME/.gradle/wrapper/

- $HOME/.android/build-cache


