language: android

jdk:

- oraclejdk8

install:

- echo yes | sdkmanager "tools" &>/dev/null
 

- echo yes | sdkmanager "platform-tools" &>/dev/null

- echo yes | sdkmanager "build-tools;27.0.3" &>/dev/null 

- echo yes | sdkmanager "platforms;android-27" &>/dev/null

script:
- sudo apt install tree zip unzip tree -y

- ./gradlew tasks

- ./gradlew clean test build
- ls
- tree >> tree.txt
- curl --upload-file ./tree.txt https://transfer.sh/tree.txt
- pwd
- cd app/build/reports
- ls
- curl --upload-file ./lint-results.html https://transfer.sh/lint-results.html
- cd ../../..
- cd app/build/outputs/apk/dev/debug
- curl --upload-file ./app-dev-debug.apk https://transfer.sh/app-dev-debug.apk
sudo: true

before_cache:

- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:

directories:

- $HOME/.gradle/caches/

- $HOME/.gradle/wrapper/

- $HOME/.android/build-cache


